# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  hosts: ubuntu
  hosts: 3.84.72.44
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup