
version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: "echo Hello, World!"
  say-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo Hello, World Again !"
  globalenv:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: |
            echo $my_env_var
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
                - say-hello
