
version: 2.1
#reusable code

# commands:
#   print_pipeline_id:
#     steps:
#       - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  onfail:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - run: exit 1
        - run:
            name: on error
            command: echo "Hello Error!"
            when: on_fail

  # my_job:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - print_pipeline_id


#--------------------------------------------------
      #hello world using workspace
  # save_hello_world_output:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         command: echo "Hello, World From output!">  ~/OUTPUT.txt
  #     - persist_to_workspace:
  #         root: ~/
  #         paths:
  #           - OUTPUT.txt

  # print_output_file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run: cat ~/OUTPUT.txt

  # say-hello:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         command: "echo Hello, World!"
  # say-world:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say world"
  #         command: "echo Hello, World Again !"
  # globalenv:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say world"
  #         command: |
  #           echo $my_env_var
  
workflows:
  say-hello-workflow:
    jobs:
    - onfail


     - my_job
  #     - save_hello_world_output
  #     - print_output_file:
  #         requires:
  #           - save_hello_world_output
      # - say-hello
      # - say-world:
      #     requires:
      #           - say-hello
      # - globalenv
