version: 2.1


orbs:
  slack: circleci/slack@4.9.3

commands:
  notify_on_failure:
    steps:
      - slack/notify:
          event: fail
          channel: cicd-pipeline
          template: basic_fail_1

  install_awscli:
    description : Install AWS CLI v2
    steps :
      - run :
         name : Install AWS CLI v2
         command : |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install
  install_ansible :
    description : Install Ansible 
    steps :
      - run :
          name : Install Ansible 
          command : |
            sudo apt update                                     
            sudo apt install software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y
  install_nodejs:
    description: Install Node.js 13
    steps:
      - run:
          name: Install Node.js 13
          command: |
            # Install Node.js LTS version as our base Node.js version
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt install -y nodejs
            
            # Use n version manager to use Node.js v13.8.0
            sudo npm install --global n
            sudo n 13.8.0
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      Workflow_ID:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:


  #automate ansible 
  #  configure_infrastructure: 
  #   docker:
  #     - image: python:3.7-alpine3.11
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints: ["4e:25:d1:5a:5d:f5:fc:a2:d8:e6:bd:f7:1e:61:e7:7e"] # You can get this ID in the section where you registered the SSH Key
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           # install the dependencies needed for your playbook
  #           apk add --update ansible 
  #     - run:
  #         name: Configure server
  #         command: |
  #           ansible-playbook -i inventory.txt remotemain.yml






  #Infrastructure pipeline
  # Exercise - Rollback
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
              --region us-east-1

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Test job
          # Fail the job intentionally to simulate an error.
          command:  return 1
      - destroy_environment 



  # onfail:
  #     docker:
  #       - image: circleci/node:13.8.0
  #     steps:
  #       - run: exit 1
  #       - run:
  #           name: on error
  #           command: echo "Hello Error!"
  #           when: on_fail

  # my_job:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - print_pipeline_id


#--------------------------------------------------
      #hello world using workspace
  # save_hello_world_output:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         command: echo "Hello, World From output!">  ~/OUTPUT.txt
  #     - persist_to_workspace:
  #         root: ~/
  #         paths:
  #           - OUTPUT.txt

  # print_output_file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run: cat ~/OUTPUT.txt

  # say-hello:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run:
  #         command: "echo Hello, World!"
  # say-world:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say world"
  #         command: "echo Hello, World Again !"
  # globalenv:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say world"
  #         command: |
  #           echo $my_env_var
  
workflows:
  say-hello-workflow:
    jobs:
      # - configure_infrastructure
      
      - create_infrastructure
      - smoke_test



    # - onfail
     # - my_job
  #     - save_hello_world_output
  #     - print_output_file:
  #         requires:
  #           - save_hello_world_output
      # - say-hello
      # - say-world:
      #     requires:
      #           - say-hello
      # - globalenv
